import styles from "../legal.module.css";

export const metadata = {
  title: "Terms of Service | Restaurant Standards",
};

export default function TermsPage() {
  return (
    <div className={styles.page}>
      <h1 className={styles.pageTitle}>Terms of Service</h1>
      <p className={styles.updated}>Last updated: February 2026</p>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Acceptance of Terms</h2>
        <p className={styles.paragraph}>
          By accessing and using restaurantstandards.com (the "Site"), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you should not use the Site. The Site is operated by Informative Media ("we," "us," or "our").
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Use of the Site</h2>
        <p className={styles.paragraph}>
          The Site provides restaurant training content, educational materials, and related tools for informational and professional development purposes. You may access and use the Site for lawful purposes consistent with these terms. You agree not to misuse the Site, interfere with its operation, or attempt to access it through unauthorized means.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Intellectual Property</h2>
        <p className={styles.paragraph}>
          All content on this Site, including but not limited to text, graphics, images, training materials, standards content, course content, and software, is the property of Informative Media and is protected by applicable copyright and intellectual property laws. You may not reproduce, distribute, modify, or create derivative works from any content on this Site without prior written consent.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>AI Training Agent</h2>
        <p className={styles.paragraph}>
          The Site includes an AI-powered training assistant that provides guidance based on the Restaurant Standards system. Responses generated by the AI agent are for educational and training purposes only. They do not constitute professional advice. We do not guarantee the accuracy or completeness of AI-generated responses and recommend using them as a supplement to, not a replacement for, professional training and judgment.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Disclaimer of Warranties</h2>
        <p className={styles.paragraph}>
          The Site and its content are provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the Site will be uninterrupted, error-free, or free of harmful components. We make no representations about the accuracy or reliability of any content on the Site.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Limitation of Liability</h2>
        <p className={styles.paragraph}>
          To the fullest extent permitted by law, Informative Media shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the Site. This includes, without limitation, damages for loss of profits, data, or other intangible losses.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>External Links</h2>
        <p className={styles.paragraph}>
          The Site may contain links to third-party websites that are not owned or controlled by us. We are not responsible for the content, privacy policies, or practices of any third-party sites. Visiting external links is at your own risk.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Changes to These Terms</h2>
        <p className={styles.paragraph}>
          We reserve the right to modify these Terms of Service at any time. Changes will be posted on this page with an updated revision date. Your continued use of the Site after changes are posted constitutes acceptance of the revised terms.
        </p>
      </section>

      <section className={styles.section}>
        <h2 className={styles.sectionTitle}>Contact</h2>
        <p className={styles.paragraph}>
          If you have questions about these Terms of Service, you may contact us through{" "}
          <a href="https://informativemedia.com" target="_blank" rel="noopener noreferrer" className={styles.link}>
            Informative Media
          </a>.
        </p>
      </section>
    </div>
  );
}